# 根据 schema 提供自动补全
"$schema" = 'https://starship.rs/config-schema.json'

# 在提示符之间插入空行
add_newline = false

# 将提示符中的 '❯' 替换为 '➜'
[character] # 此组件名称为 'character'
success_symbol = '[➜](bold green)'
error_symbol = '[➜](bold red)'

# 禁用 'package' 组件，将其隐藏
[package]
disabled = true

[directory]
truncation_length = 0
truncate_to_repo = false
